const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("metro", {
  authStatus: () => ipcRenderer.invoke("auth:status"),
  login: () => ipcRenderer.invoke("auth:login"),
  logout: () => ipcRenderer.invoke("auth:logout"),
  clearAll: () => ipcRenderer.invoke("auth:clear-all"),
  accountProfiles: () => ipcRenderer.invoke("auth:profiles"),
  saveAccountProfile: () => ipcRenderer.invoke("auth:save-profile"),
  switchAccountProfile: (profileId) => ipcRenderer.invoke("auth:switch-profile", profileId),
  deleteAccountProfile: (profileId) => ipcRenderer.invoke("auth:delete-profile", profileId),
  onAuthChanged: (callback) => ipcRenderer.on("auth:changed", (_event, value) => callback(value)),
  onError: (callback) => ipcRenderer.on("app:error", (_event, value) => callback(value)),
  copyText: (text) => ipcRenderer.invoke("app:copy-text", text),
  saveTextFile: (payload) => ipcRenderer.invoke("app:save-text-file", payload),
  closeWindow: () => ipcRenderer.invoke("app:close-window"),
  reloadWindow: () => ipcRenderer.invoke("app:reload-window"),
  setWindowFullscreen: (value) => ipcRenderer.invoke("app:set-fullscreen", value),
  setTitleBarTheme: (payload) => ipcRenderer.invoke("app:set-titlebar-theme", payload),
  extractArtworkColor: (urls) => ipcRenderer.invoke("app:extract-artwork-color", urls),
  setExpandedLyricsKeepAwake: (enabled) => ipcRenderer.invoke("app:set-expanded-lyrics-keep-awake", enabled),
  getPreferences: () => ipcRenderer.invoke("preferences:get"),
  setPreference: (payload) => ipcRenderer.invoke("preferences:set", payload),
  toggleMiniPlayer: (state) => ipcRenderer.invoke("mini:toggle", { state }),
  openMiniPlayer: (state) => ipcRenderer.invoke("mini:open", { state }),
  closeMiniPlayer: () => ipcRenderer.invoke("mini:close"),
  miniPlayerReady: () => ipcRenderer.invoke("mini:ready"),
  miniPlayerStatus: () => ipcRenderer.invoke("mini:status"),
  updateMiniPlayerState: (payload) => ipcRenderer.invoke("mini:update-state", payload),
  sendMiniPlayerCommand: (payload) => ipcRenderer.invoke("mini:command", payload),
  setMiniAlwaysOnTop: (value) => ipcRenderer.invoke("mini:set-always-on-top", value),
  startMiniDrag: (payload) => ipcRenderer.send("mini:drag-start", payload),
  moveMiniDrag: (payload) => ipcRenderer.send("mini:drag-move", payload),
  endMiniDrag: () => ipcRenderer.send("mini:drag-end"),
  showMainWindow: () => ipcRenderer.invoke("mini:show-main"),
  onMiniPlayerState: (callback) => ipcRenderer.on("mini:state", (_event, value) => callback(value)),
  onMiniPlayerWindowState: (callback) => ipcRenderer.on("mini:window-state", (_event, value) => callback(value)),
  onMiniPlayerCommand: (callback) => ipcRenderer.on("mini:command", (_event, value) => callback(value)),
  onMiniPlayerClosed: (callback) => ipcRenderer.on("mini:closed", () => callback()),
  trayReady: () => ipcRenderer.invoke("tray:ready"),
  hideTray: () => ipcRenderer.invoke("tray:hide"),
  onTrayState: (callback) => ipcRenderer.on("tray:state", (_event, value) => callback(value)),

  localMusic: () => ipcRenderer.invoke("local-music:list"),
  selectLocalMusicFolder: () => ipcRenderer.invoke("local-music:select-folder"),
  rescanLocalMusic: (folderPath) => ipcRenderer.invoke("local-music:rescan", folderPath),
  clearLocalMusic: () => ipcRenderer.invoke("local-music:clear"),
  onLocalMusicProgress: (callback) => ipcRenderer.on("local-music:progress", (_event, value) => callback(value)),
  getShortcuts: () => ipcRenderer.invoke("shortcuts:get"),
  setShortcuts: (value) => ipcRenderer.invoke("shortcuts:set", value),
  updateStatus: () => ipcRenderer.invoke("update:status"),
  checkForUpdates: (repository) => ipcRenderer.invoke("update:check", repository),
  downloadUpdate: (installAfterDownload = false) => ipcRenderer.invoke("update:download", { installAfterDownload }),
  installUpdate: () => ipcRenderer.invoke("update:install"),
  onUpdateEvent: (callback) => ipcRenderer.on("update:event", (_event, value) => callback(value)),

  search: (query) => ipcRenderer.invoke("ytm:search", query),
  recognizeMusic: (payload) => ipcRenderer.invoke("music:recognize", payload),
  recognitionHistory: () => ipcRenderer.invoke("music:recognition-history"),
  removeRecognitionHistory: (id) => ipcRenderer.invoke("music:remove-recognition", id),
  clearRecognitionHistory: () => ipcRenderer.invoke("music:clear-recognition-history"),
  searchArtists: (query) => ipcRenderer.invoke("ytm:search-artists", query),
  home: (payload) => ipcRenderer.invoke("ytm:home", payload),
  explore: () => ipcRenderer.invoke("ytm:explore"),
  charts: () => ipcRenderer.invoke("ytm:charts"),
  newReleases: () => ipcRenderer.invoke("ytm:new-releases"),
  moods: () => ipcRenderer.invoke("ytm:moods"),
  browse: (payload) => ipcRenderer.invoke("ytm:browse", payload),
  artist: (payload) => ipcRenderer.invoke("ytm:artist", payload),
  collection: (payload) => ipcRenderer.invoke("ytm:collection", payload),
  continue: (payload) => ipcRenderer.invoke("ytm:continue", payload),
  feedback: (payload) => ipcRenderer.invoke("ytm:feedback", payload),
  likeVideo: (videoId) => ipcRenderer.invoke("ytm:like-video", videoId),
  unlikeVideo: (videoId) => ipcRenderer.invoke("ytm:unlike-video", videoId),
  subscribeChannel: (payload) => ipcRenderer.invoke("ytm:subscribe-channel", payload),
  addToPlaylist: (payload) => ipcRenderer.invoke("ytm:add-to-playlist", payload),
  createPlaylist: (payload) => ipcRenderer.invoke("ytm:create-playlist", payload),
  likedSongs: () => ipcRenderer.invoke("ytm:liked-songs"),
  librarySongs: () => ipcRenderer.invoke("ytm:library-songs"),
  libraryOverview: () => ipcRenderer.invoke("ytm:library-overview"),
  savedPlaylists: () => ipcRenderer.invoke("ytm:saved-playlists"),
  playlist: (playlistId) => ipcRenderer.invoke("ytm:playlist", playlistId),
  queue: (payload) => ipcRenderer.invoke("ytm:queue", payload),
  playback: (payload) => ipcRenderer.invoke("ytm:playback", payload),
  lyrics: (track, options) => ipcRenderer.invoke("lyrics:find", { track, options }),
  searchLyrics: (track, options) => ipcRenderer.invoke("lyrics:search", { track, options }),
  translateLyrics: (lines, options) => ipcRenderer.invoke("lyrics:translate", { lines, options }),
  romanizeLyrics: (lines) => ipcRenderer.invoke("lyrics:romanize", { lines }),
  cachedLyrics: (trackId) => ipcRenderer.invoke("lyrics:cache-get", trackId),
  cacheLyrics: (trackId, result) => ipcRenderer.invoke("lyrics:cache-save", { trackId, result }),
  clearCachedLyrics: (trackId) => ipcRenderer.invoke("lyrics:cache-clear", trackId),
  getQueue: () => ipcRenderer.invoke("queue:get"),
  setQueue: (queue) => ipcRenderer.invoke("queue:set", queue),
  getPlaybackSession: () => ipcRenderer.invoke("session:get"),
  savePlaybackSession: (payload) => ipcRenderer.invoke("session:save", payload),
  savePlaybackSessionSync: (payload) => ipcRenderer.sendSync("session:save-sync", payload),
  cacheList: () => ipcRenderer.invoke("cache:list"),
  cacheGet: (videoId) => ipcRenderer.invoke("cache:get", videoId),
  cacheTrack: (payload) => ipcRenderer.invoke("cache:save-track", payload),
  cacheRemove: (videoId) => ipcRenderer.invoke("cache:remove", videoId),
  cacheClear: () => ipcRenderer.invoke("cache:clear"),
  openCacheFolder: () => ipcRenderer.invoke("cache:open-folder"),

  // ── NEW: History ──
  history: () => ipcRenderer.invoke("ytm:history"),
  removeFromHistory: (feedbackToken) => ipcRenderer.invoke("ytm:history-remove", feedbackToken),

  // ── NEW: Podcast ──
  podcast: (browseId) => ipcRenderer.invoke("ytm:podcast", browseId),
  podcastContinuation: (token) => ipcRenderer.invoke("ytm:podcast-continue", token),

  // ── NEW: Playlist CRUD ──
  removeFromPlaylist: (payload) => ipcRenderer.invoke("ytm:remove-from-playlist", payload),
  renamePlaylist: (payload) => ipcRenderer.invoke("ytm:rename-playlist", payload),
  deletePlaylist: (playlistId) => ipcRenderer.invoke("ytm:delete-playlist", playlistId),
  moveSongInPlaylist: (payload) => ipcRenderer.invoke("ytm:move-song-in-playlist", payload),

  // ── NEW: Search Suggestions ──
  searchSuggestions: (query) => ipcRenderer.invoke("ytm:search-suggestions", query),

  // ── NEW: Transcript ──
  getTranscript: (videoId) => ipcRenderer.invoke("ytm:get-transcript", videoId),

  // ── NEW: Desktop Lyrics Widget ──
  toggleLyricWindow: () => ipcRenderer.invoke("lyric:toggle"),
  lyricWindowStatus: () => ipcRenderer.invoke("lyric:status"),
  moveLyricWindowTop: () => ipcRenderer.invoke("lyric:move-top"),
  updateLyricText: (payload) => ipcRenderer.invoke("lyric:update", payload),
  setIgnoreMouse: (ignore, options) => ipcRenderer.invoke("lyric:ignore-mouse", ignore, options),
  onLyricUpdate: (callback) => ipcRenderer.on("lyric:changed", (_event, text) => callback(text)),
  onLyricWidgetClosed: (callback) => ipcRenderer.on("lyric:widget-closed", () => callback()),
  onFullscreenChanged: (callback) => ipcRenderer.on("app:fullscreen-changed", (_event, value) => callback(value))
});
